const ErrorStatus = {
  FAILED_CONNECT: 'FAILED_CONNECT',
  FAILED_TRAIN: 'FAILED_TRAIN',
  FAILED_GET: 'FAILED_GET',
  FAILED_CREATE: 'FAILED_CREATE',
  FAILED_DELETE: 'FAILED_DELETE',
  FAILED_UPDATE: 'FAILED_UPDATE',
  INVALID_PARAMETER: 'INVALID_PARAMETER'
}

export default ErrorStatus
